// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GLHelpers")>]
[<assembly: AssemblyProductAttribute("GLHelpers")>]
[<assembly: AssemblyDescriptionAttribute("OpenTK and WebGL helpers")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GLHelpers"
    let [<Literal>] AssemblyProduct = "GLHelpers"
    let [<Literal>] AssemblyDescription = "OpenTK and WebGL helpers"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
